# Generated by Django 5.2.4 on 2025-07-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_project', models.CharField(max_length=255)),
                ('project_address', models.CharField(max_length=500)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_number', models.CharField(max_length=20)),
            ],
        ),
    ]
